/**
 * Generated by orval v7.9.0 🍺  
 * Do not edit manually.  
 * Rap_app  
 * Documentation complète de l'API Rap_App pour l'application mobile et web.  
 * OpenAPI spec version: 1.0.0
 */

/**
 * 🏫 Sérialiseur du modèle Centre, basé sur `to_serializable_dict`.
 */
export interface Centre {
  readonly id?: number;

  /** Date et heure de création de l'enregistrement */
  readonly created_at?: string;

  /** Date et heure de la dernière modification */
  readonly updated_at?: string;

  /** Indique si l'objet est actif ou archivé */
  is_active?: boolean;

  /**
   * Nom complet du centre de formation (doit être unique)
   * @maxLength 255
   */
  nom: string;

  /**
   * Code postal à 5 chiffres du centre
   * @maxLength 5
   * @nullable
   * @pattern ^\d{5}$
   */
  code_postal?: string | null;

  /** Adresse complète du centre (calculée côté serveur) */
  readonly full_address?: string;

  /** Nombre de PrepaCompGlobal associés (calculé) */
  readonly nb_prepa_comp_global?: number;
}

/**
 * ✍️ Données requises pour créer ou mettre à jour un centre.
 */
export interface CentreRequest {
  /** Indique si l'objet est actif ou archivé */
  is_active?: boolean;

  /**
   * Nom complet du centre de formation (doit être unique)
   * @minLength 1
   * @maxLength 255
   */
  nom: string;

  /**
   * Code postal à 5 chiffres du centre
   * @maxLength 5
   * @nullable
   * @pattern ^\d{5}$
   */
  code_postal?: string | null;
}

/**
 * 🔍 Paramètres de filtrage et pagination pour la liste des centres
 */
export type CentresListParams = {
  /** Filtre sur le code postal */
  code_postal?: string;

  /** Filtre sur le nom */
  nom?: string;

  /**
   * Champ de tri (ex : nom, -created_at)
   */
  ordering?: string;

  /**
   * Page courante
   */
  page?: number;

  /**
   * Nombre de résultats par page
   */
  page_size?: number;

  /**
   * Recherche texte libre
   */
  search?: string;
};

/**
 * 📄 Réponse paginée contenant une liste de centres
 */
export interface PaginatedCentreList {
  /** Nombre total de résultats */
  count?: number;

  /** Lien vers la page suivante (null si aucune) */
  next?: string | null;

  /** Lien vers la page précédente (null si aucune) */
  previous?: string | null;

  /** Résultats de la page courante */
  results?: Centre[];
}
/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Rap_app
 * Documentation complète de l'API Rap_App pour l'application mobile et web.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Sérialiseur du modèle Centre, basé sur to_serializable_dict.
 */
export interface PatchedCentreRequest {
  /** Indique si l'objet est actif ou archivé */
  is_active?: boolean;
  /**
   * Nom complet du centre de formation (doit être unique)
   * @minLength 1
   * @maxLength 255
   */
  nom?: string;
  /**
   * Code postal à 5 chiffres du centre
   * @maxLength 5
   * @nullable
   * @pattern ^\d{5}$
   */
  code_postal?: string | null;
}
