/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Rap_app
 * Documentation complète de l'API Rap_App pour l'application mobile et web.
 * OpenAPI spec version: 1.0.0
 */

/**
 * 💬 Serializer principal pour les commentaires de formation.
 */
export interface Commentaire {
  readonly id?: number;
  /** Formation à laquelle ce commentaire est associé */
  formation: number;
  /** Texte du commentaire (le HTML est automatiquement nettoyé) */
  contenu: string;
  /**
   * Pourcentage de saturation perçue dans la formation (entre 0 et 100)
   * @minimum 0
   * @maximum 100
   * @nullable
   */
  saturation?: number | null;
  /** Date et heure de création de l'enregistrement */
  readonly created_at?: string;
  /** Date et heure de la dernière modification */
  readonly updated_at?: string;
}

/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Rap_app
 * Documentation complète de l'API Rap_App pour l'application mobile et web.
 * OpenAPI spec version: 1.0.0
 */

/**
 * 💬 Serializer principal pour les commentaires de formation.
 */
export interface CommentaireRequest {
  /** Formation à laquelle ce commentaire est associé */
  formation: number;
  /**
   * Texte du commentaire (le HTML est automatiquement nettoyé)
   * @minLength 1
   */
  contenu: string;
  /**
   * Pourcentage de saturation perçue dans la formation (entre 0 et 100)
   * @minimum 0
   * @maximum 100
   * @nullable
   */
  saturation?: number | null;
}

/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Rap_app
 * Documentation complète de l'API Rap_App pour l'application mobile et web.
 * OpenAPI spec version: 1.0.0
 */

export type CommentairesListParams = {
/**
 * Which field to use when ordering the results.
 */
ordering?: string;
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Number of results to return per page.
 */
page_size?: number;
/**
 * A search term.
 */
search?: string;
};

/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Rap_app
 * Documentation complète de l'API Rap_App pour l'application mobile et web.
 * OpenAPI spec version: 1.0.0
 */
export interface PaginatedCommentaireList {
  count?: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results?: Commentaire[];
}
/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Rap_app
 * Documentation complète de l'API Rap_App pour l'application mobile et web.
 * OpenAPI spec version: 1.0.0
 */

/**
 * 💬 Serializer principal pour les commentaires de formation.
 */
export interface PatchedCommentaireRequest {
  /** Formation à laquelle ce commentaire est associé */
  formation?: number;
  /**
   * Texte du commentaire (le HTML est automatiquement nettoyé)
   * @minLength 1
   */
  contenu?: string;
  /**
   * Pourcentage de saturation perçue dans la formation (entre 0 et 100)
   * @minimum 0
   * @maximum 100
   * @nullable
   */
  saturation?: number | null;
}
