/**
 * Generated by orval v7.9.0 🍺  
 * Do not edit manually.  
 * Rap_app  
 * Documentation complète de l'API Rap_App pour l'application mobile et web.  
 * OpenAPI spec version: 1.0.0
 */

/* ========================================================
 * 🧾 ENUMS CENTRALISÉS : type de document
 * ======================================================== */

/**
 * Catégorie du document (PDF, Image, Contrat...)
 */
export const DOCUMENT_TYPE = {
  pdf: 'pdf',
  image: 'image',
  contrat: 'contrat',
  autre: 'autre',
} as const;

/**
 * Catégorie du document (PDF, Image, Contrat...) utilisée en lecture seule.
 */
export type DocumentTypeDocument = keyof typeof DOCUMENT_TYPE;

/**
 * Catégorie du document pour les requêtes POST/PUT
 */
export type DocumentRequestTypeDocument = keyof typeof DOCUMENT_TYPE;

/**
 * Catégorie du document pour les requêtes PATCH
 */
export type PatchedDocumentRequestTypeDocument = keyof typeof DOCUMENT_TYPE;

/* ========================================================
 * 📄 INTERFACES DOCUMENT
 * ======================================================== */

/**
 * 📄 Serializer principal pour les documents liés à une formation.
 */
export interface Document {
  readonly id?: number;

  /**
   * Nom lisible du document (sera nettoyé automatiquement)
   * @maxLength 255
   */
  nom_fichier: string;

  /** Fichier téléversé (PDF, image, doc...) */
  fichier: string;

  /** Catégorie du document (PDF, Image, Contrat...) */
  type_document?: DocumentTypeDocument;

  /** Nom lisible de la catégorie */
  readonly type_document_display?: string;

  /**
   * Taille du fichier en kilo-octets (calculée automatiquement)
   * @nullable
   */
  readonly taille_fichier?: number | null;

  /** Taille lisible (ex : "1.2 Mo") */
  readonly taille_readable?: string;

  /**
   * Type MIME détecté automatiquement (ex : application/pdf)
   * @nullable
   */
  readonly mime_type?: string | null;

  /** Extension du fichier (ex : .pdf) */
  readonly extension?: string;

  /** Classe d'icône CSS */
  readonly icon_class?: string;

  /** URL de téléchargement direct */
  readonly download_url?: string;

  /** ID de la formation liée à ce document */
  formation: number;

  /** Date et heure de création de l'enregistrement */
  readonly created_at?: string;

  /** Nom ou ID de l'utilisateur ayant créé le document */
  readonly created_by?: string;
}

/**
 * 📄 Données nécessaires pour créer ou mettre à jour un document
 */
export interface DocumentRequest {
  /**
   * Nom lisible du document (sera nettoyé automatiquement)
   * @minLength 1
   * @maxLength 255
   */
  nom_fichier: string;

  /** Fichier téléversé (PDF, image, doc...) */
  fichier: Blob;

  /** Catégorie du document (PDF, Image, Contrat...) */
  type_document?: DocumentRequestTypeDocument;

  /** ID de la formation liée à ce document */
  formation: number;
}

/**
 * 🛠 Données partielles pour un patch de document
 */
export interface PatchedDocumentRequest {
  /**
   * Nom lisible du document (sera nettoyé automatiquement)
   * @minLength 1
   * @maxLength 255
   */
  nom_fichier?: string;

  /** Fichier téléversé (PDF, image, doc...) */
  fichier?: Blob;

  /** Catégorie du document (PDF, Image, Contrat...) */
  type_document?: PatchedDocumentRequestTypeDocument;

  /** ID de la formation liée à ce document */
  formation?: number;
}

/* ========================================================
 * 📋 PARAMÈTRES DE LISTE / PAGINATION
 * ======================================================== */

/**
 * 🔍 Paramètres pour paginer la liste de tous les documents
 */
export type DocumentsListParams = {
  /**
   * A page number within the paginated result set.
   */
  page?: number;

  /**
   * Number of results to return per page.
   */
  page_size?: number;
};

/**
 * 🔍 Paramètres pour filtrer les documents d'une formation spécifique
 */
export type DocumentsParFormationRetrieveParams = {
  /**
   * ID de la formation
   */
  formation: number;
};

/**
 * 📄 Résultat paginé de la liste des documents
 */
export interface PaginatedDocumentList {
  count?: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results?: Document[];
}
