/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Rap_app
 * Documentation complète de l'API Rap_App pour l'application mobile et web.
 * OpenAPI spec version: 1.0.0
 */

/* ============================================
 * 📦 ENUMS
 * ============================================
 */

/**
 * 🎯 Type de partenaire (entreprise, institutionnel, personne)
 */
export const PARTENAIRE_TYPE = {
  entreprise: 'entreprise',
  partenaire: 'partenaire',
  personne: 'personne',
} as const;

export type PartenaireType = keyof typeof PARTENAIRE_TYPE;

/**
 * 🧭 Catégorie d'action (partenariat, coaching, etc.)
 */
export const PARTENAIRE_ACTIONS = {
  recrutement_emploi: 'recrutement_emploi',
  recrutement_stage: 'recrutement_stage',
  recrutement_apprentissage: 'recrutement_apprentissage',
  presentation_metier_entreprise: 'presentation_metier_entreprise',
  visite_entreprise: 'visite_entreprise',
  coaching: 'coaching',
  partenariat: 'partenariat',
  autre: 'autre',
  non_definie: 'non_definie',
  '': '',
} as const;

export type PartenaireActions = keyof typeof PARTENAIRE_ACTIONS | '';

/* ============================================
 * 📄 INTERFACES
 * ============================================
 */

/**
 * 🤝 Sérialiseur principal pour un partenaire (lecture seule).
 */
export interface Partenaire {
  readonly id?: number;

  /** Nom unique de l'entité partenaire */
  nom: string;

  /** Type de partenaire (entreprise, institutionnel, personne) */
  type?: PartenaireType;
  readonly type_display?: string;

  /** Secteur d'activité principal */
  secteur_activite?: string | null;

  /** Adresse postale (rue, numéro) */
  street_name?: string | null;

  /** Code postal (5 chiffres) */
  zip_code?: string | null;

  /** Ville */
  city?: string | null;

  /** Pays (France par défaut) */
  country?: string | null;

  /** Nom complet du contact */
  contact_nom?: string | null;

  /** Fonction occupée par le contact */
  contact_poste?: string | null;

  /** Numéro de téléphone au format français */
  contact_telephone?: string | null;

  /** Adresse email du contact */
  contact_email?: string | null;

  /** URL du site web */
  website?: string | null;

  /** Réseau social (LinkedIn, etc.) */
  social_network_url?: string | null;

  /** Catégorie d'action */
  actions?: PartenaireActions;
  readonly actions_display?: string;

  /** Détails sur les actions menées */
  action_description?: string | null;

  /** Description libre du partenaire */
  description?: string | null;

  /** Identifiant URL unique généré automatiquement */
  readonly slug?: string | null;

  /** Date de création */
  readonly created_at?: string;

  /** Date de modification */
  readonly updated_at?: string;

  /** Statut d'activation du partenaire */
  is_active?: boolean;
}

/**
 * ✍️ Données envoyées pour créer ou modifier un partenaire.
 */
export interface PartenaireRequest {
  nom: string;
  type?: PartenaireType;
  secteur_activite?: string | null;
  street_name?: string | null;
  zip_code?: string | null;
  city?: string | null;
  country?: string | null;
  contact_nom?: string | null;
  contact_poste?: string | null;
  contact_telephone?: string | null;
  contact_email?: string | null;
  website?: string | null;
  social_network_url?: string | null;
  actions?: PartenaireActions;
  action_description?: string | null;
  description?: string | null;
  is_active?: boolean;
}

/**
 * 🛠 Données pour mise à jour partielle d'un partenaire.
 */
export interface PatchedPartenaireRequest {
  /**
   * Nom unique de l'entité partenaire
   * @minLength 1
   * @maxLength 255
   */
  nom?: string;

  /** Type de partenaire (entreprise, institutionnel, personne) */
  type?: PartenaireType;

  /**
   * Secteur d'activité principal
   * @maxLength 255
   * @nullable
   */
  secteur_activite?: string | null;

  /**
   * Adresse postale (rue, numéro)
   * @maxLength 200
   * @nullable
   */
  street_name?: string | null;

  /**
   * Code postal (5 chiffres)
   * @maxLength 5
   * @nullable
   * @pattern ^[0-9]{5}$
   */
  zip_code?: string | null;

  /**
   * Ville
   * @maxLength 100
   * @nullable
   */
  city?: string | null;

  /**
   * Pays (France par défaut)
   * @maxLength 100
   * @nullable
   */
  country?: string | null;

  /**
   * Nom complet du contact
   * @maxLength 255
   * @nullable
   */
  contact_nom?: string | null;

  /**
   * Fonction occupée par le contact
   * @maxLength 255
   * @nullable
   */
  contact_poste?: string | null;

  /**
   * Numéro de téléphone au format français
   * @maxLength 20
   * @nullable
   * @pattern ^(0[1-9]\d{8})$|^(?:\+33|0033)[1-9]\d{8}$
   */
  contact_telephone?: string | null;

  /**
   * Adresse email du contact
   * @maxLength 254
   * @nullable
   */
  contact_email?: string | null;

  /**
   * URL du site web (doit commencer par http:// ou https://)
   * @maxLength 200
   * @nullable
   * @pattern ^(http|https)://
   */
  website?: string | null;

  /**
   * URL d’un réseau social (LinkedIn, etc.)
   * @maxLength 200
   * @nullable
   */
  social_network_url?: string | null;

  /**
   * Catégorie d'action (partenariat, coaching, etc.)
   * @nullable
   */
  actions?: PartenaireActions;

  /**
   * Détails sur les actions menées
   * @nullable
   */
  action_description?: string | null;

  /**
   * Description libre du partenaire
   * @nullable
   */
  description?: string | null;

  /** Indique si l'objet est actif ou archivé */
  is_active?: boolean;
}

/**
 * 📋 Paramètres de filtrage pour la liste des partenaires.
 */
export interface PartenairesListParams {
  ordering?: string;
  page?: number;
  page_size?: number;
  search?: string;
}

/**
 * 📄 Liste paginée de partenaires.
 */
export interface PaginatedPartenaireList {
  count?: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results?: Partenaire[];
}
