/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Rap_app
 * Documentation complète de l'API Rap_App pour l'application mobile et web.
 * OpenAPI spec version: 1.0.0
 */

/* ============================================
 * 📄 INTERFACES
 * ============================================
 */

/**
 * 📊 Serializer principal pour PrepaCompGlobal.
 * Utilise `to_serializable_dict` pour l’API.
 */
export interface PrepaCompGlobal {
  readonly id?: number;

  /**
   * Centre de formation concerné
   * @nullable
   */
  centre: number | null;

  /**
   * Année de référence pour le bilan
   * @minimum 0
   * @maximum 2147483647
   */
  annee?: number;

  /**
   * Total des candidats cumulés sur l’année
   * @minimum 0
   * @maximum 2147483647
   */
  total_candidats?: number;

  /**
   * Total des prescriptions enregistrées
   * @minimum 0
   * @maximum 2147483647
   */
  total_prescriptions?: number;

  /**
   * Nombre total d’adhésions
   * @minimum 0
   * @maximum 2147483647
   */
  adhesions?: number;

  /**
   * Nombre de personnes présentes en information collective
   * @minimum 0
   * @maximum 2147483647
   */
  total_presents?: number;

  /**
   * Nombre total de places ouvertes
   * @minimum 0
   * @maximum 2147483647
   */
  total_places_ouvertes?: number;

  /**
   * Objectif annuel de préparation
   * @minimum 0
   * @maximum 2147483647
   */
  objectif_annuel_prepa?: number;

  /**
   * Objectif hebdomadaire de préparation
   * @minimum 0
   * @maximum 2147483647
   */
  objectif_hebdomadaire_prepa?: number;

  /**
   * Objectif annuel pour les jurys
   * @minimum 0
   * @maximum 2147483647
   */
  objectif_annuel_jury?: number;

  /**
   * Objectif mensuel pour les jurys
   * @minimum 0
   * @maximum 2147483647
   */
  objectif_mensuel_jury?: number;

  /** Date et heure de création de l'enregistrement */
  readonly created_at?: string;

  /** Date et heure de la dernière modification */
  readonly updated_at?: string;

  /**
   * Utilisateur ayant créé l'enregistrement
   * @nullable
   */
  readonly created_by?: number | null;

  /**
   * Dernier utilisateur ayant modifié l'enregistrement
   * @nullable
   */
  readonly updated_by?: number | null;

  /** Indique si l'objet est actif ou archivé */
  readonly is_active?: boolean;
}

/**
 * 📝 Requête de création ou modification complète
 */
export interface PrepaCompGlobalRequest {
  centre: number | null;
  annee?: number;
  total_candidats?: number;
  total_prescriptions?: number;
  adhesions?: number;
  total_presents?: number;
  total_places_ouvertes?: number;
  objectif_annuel_prepa?: number;
  objectif_hebdomadaire_prepa?: number;
  objectif_annuel_jury?: number;
  objectif_mensuel_jury?: number;
}

/**
 * 🛠 Requête de mise à jour partielle (PATCH)
 */
export interface PatchedPrepaCompGlobalRequest {
  centre?: number | null;
  annee?: number;
  total_candidats?: number;
  total_prescriptions?: number;
  adhesions?: number;
  total_presents?: number;
  total_places_ouvertes?: number;
  objectif_annuel_prepa?: number;
  objectif_hebdomadaire_prepa?: number;
  objectif_annuel_jury?: number;
  objectif_mensuel_jury?: number;
}

/**
 * 📋 Paramètres de pagination pour la liste des bilans globaux
 */
export interface PrepaGlobauxListParams {
  /** Numéro de page dans la pagination */
  page?: number;

  /** Nombre d'éléments par page */
  page_size?: number;
}

/**
 * 📄 Liste paginée de PrepaCompGlobal
 */
export interface PaginatedPrepaCompGlobalList {
  count?: number;

  /** URL de la page suivante */
  next?: string | null;

  /** URL de la page précédente */
  previous?: string | null;

  results?: PrepaCompGlobal[];
}
