/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Rap_app
 * Documentation complète de l'API Rap_App pour l'application mobile et web.
 * OpenAPI spec version: 1.0.0
 */

/* ============================================
 * 📦 ENUMS
 * ============================================
 */

/** Type de contact (ex: premier_contact) */
export const PROSPECTION_TYPE_CONTACT = {
  premier_contact: 'premier_contact',
  relance: 'relance',
} as const;

export type ProspectionTypeContact = keyof typeof PROSPECTION_TYPE_CONTACT;

/** Motif de la prospection */
export const PROSPECTION_MOTIF = {
  POEI: 'POEI',
  apprentissage: 'apprentissage',
  VAE: 'VAE',
  partenariat: 'partenariat',
  autre: 'autre',
} as const;

export type ProspectionMotif = keyof typeof PROSPECTION_MOTIF;

/** Objectif visé par la prospection */
export const PROSPECTION_OBJECTIF = {
  prise_contact: 'prise_contact',
  rendez_vous: 'rendez_vous',
  presentation_offre: 'presentation_offre',
  contrat: 'contrat',
  partenariat: 'partenariat',
  autre: 'autre',
} as const;

export type ProspectionObjectif = keyof typeof PROSPECTION_OBJECTIF;

/** Statut de la prospection */
export const PROSPECTION_STATUT = {
  a_faire: 'a_faire',
  en_cours: 'en_cours',
  a_relancer: 'a_relancer',
  acceptee: 'acceptee',
  refusee: 'refusee',
  annulee: 'annulee',
  non_renseigne: 'non_renseigne',
} as const;

export type ProspectionStatut = keyof typeof PROSPECTION_STATUT;

/* ============================================
 * 📄 INTERFACES
 * ============================================
 */

/**
 * 🔎 Objet de prospection (lecture seule)
 */
export interface Prospection {
  readonly id?: number;
  partenaire: number;
  readonly partenaire_nom?: string;

  /**
   * ID de la formation (optionnelle)
   * @nullable
   */
  formation?: number | null;
  readonly formation_nom?: string;

  /** Date et heure de la prospection */
  date_prospection?: string;

  /** Type de contact */
  type_contact?: ProspectionTypeContact;
  readonly type_contact_display?: string;

  /** Motif de la prospection */
  motif: ProspectionMotif;
  readonly motif_display?: string;

  /** Statut actuel */
  statut?: ProspectionStatut;
  readonly statut_display?: string;

  /** Objectif visé */
  objectif?: ProspectionObjectif;
  readonly objectif_display?: string;

  /**
   * Commentaire libre
   * @nullable
   */
  commentaire?: string | null;

  /** Date prévue de relance (optionnelle) */
  readonly prochain_contact?: string | null;

  /** Indicateurs internes */
  readonly is_active?: boolean;
  readonly relance_necessaire?: boolean;

  /** Traces de création/modification */
  readonly created_by?: string;
  readonly created_at?: string;
  readonly updated_at?: string;
}

/**
 * 📤 Requête pour créer ou modifier une prospection
 */
export interface ProspectionRequest {
  partenaire: number;
  formation?: number | null;
  date_prospection?: string;
  type_contact?: ProspectionTypeContact;
  motif: ProspectionMotif;
  statut?: ProspectionStatut;
  objectif?: ProspectionObjectif;
  commentaire?: string | null;
}

/**
 * 🛠 Requête de mise à jour partielle
 */
export interface PatchedProspectionRequest {
  partenaire?: number;
  formation?: number | null;
  date_prospection?: string;
  type_contact?: ProspectionTypeContact;
  motif?: ProspectionMotif;
  statut?: ProspectionStatut;
  objectif?: ProspectionObjectif;
  commentaire?: string | null;
}

/* ============================================
 * 📑 PARAMS & PAGINATION
 * ============================================
 */

/**
 * 🔍 Paramètres de filtrage de prospection
 */
export interface ProspectionsListParams {
  formation?: number;
  ordering?: string;
  page?: number;
  page_size?: number;
  partenaire?: number;
  search?: string;
  statut?: string;
}

/**
 * 📄 Liste paginée de prospections
 */
export interface PaginatedProspectionList {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: Prospection[];
}
