/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Rap_app
 * Documentation complète de l'API Rap_App pour l'application mobile et web.
 * OpenAPI spec version: 1.0.0
 */

/* ENUMS */

/**
 * Liste des noms internes possibles pour les statuts.
 */
export const statutNomValues = {
  non_defini: 'non_defini',
  recrutement_en_cours: 'recrutement_en_cours',
  formation_en_cours: 'formation_en_cours',
  formation_a_annuler: 'formation_a_annuler',
  formation_a_repousser: 'formation_a_repousser',
  formation_annulee: 'formation_annulee',
  pleine: 'pleine',
  quasi_pleine: 'quasi_pleine',
  autre: 'autre',
} as const;

export type StatutNom = keyof typeof statutNomValues;
export type StatutRequestNom = StatutNom;
export type PatchedStatutRequestNom = StatutNom;

/* PARAMÈTRES DE LISTE */

/**
 * Paramètres de pagination pour la liste des statuts.
 */
export type StatutsListParams = {
  /** A page number within the paginated result set. */
  page?: number;
  /** Number of results to return per page. */
  page_size?: number;
};

/* INTERFACES */

/**
 * Sérialiseur pour le modèle Statut.
 *
 * - Le champ `libelle` affiche un nom lisible, en particulier pour le statut 'Autre'.
 * - Le champ `badge_html` fournit une représentation visuelle colorée pour l'interface.
 */
export interface Statut {
  /** ID unique du statut. */
  readonly id?: number;
  /** Nom interne du statut (valeurs définies en base). */
  nom: StatutNom;
  /** Couleur hexadécimale du badge (#RRGGBB). */
  couleur?: string;
  /** Texte personnalisé pour le statut 'Autre'. */
  description_autre?: string;
  /** Libellé affiché du statut (remplace 'Autre' par une description personnalisée si définie). */
  readonly libelle?: string;
  /** Code HTML pour un badge coloré représentant le statut visuellement. */
  readonly badge_html?: string;
  /** Date de création. */
  readonly created_at?: string;
  /** Dernière mise à jour. */
  readonly updated_at?: string;
  /**
   * Nom de l'utilisateur ayant créé ce statut.
   * @nullable
   */
  readonly created_by?: string | null;
  /**
   * Nom de l'utilisateur ayant modifié ce statut.
   * @nullable
   */
  readonly updated_by?: string | null;
  /** Statut actif ou désactivé (suppression logique). */
  readonly is_active?: boolean;
}

/**
 * Payload de création d'un Statut.
 */
export interface StatutRequest {
  /** Nom interne du statut (valeurs définies en base). */
  nom: StatutRequestNom;
  /** Couleur hexadécimale du badge (#RRGGBB). */
  couleur?: string;
  /** Texte personnalisé pour le statut 'Autre'. */
  description_autre?: string;
}

/**
 * Payload de mise à jour partielle (PATCH) d'un Statut.
 */
export interface PatchedStatutRequest {
  /** Nom interne du statut (valeurs définies en base). */
  nom?: PatchedStatutRequestNom;
  /** Couleur hexadécimale du badge (#RRGGBB). */
  couleur?: string;
  /** Texte personnalisé pour le statut 'Autre'. */
  description_autre?: string;
}

/**
 * Résultat paginé pour la liste des statuts.
 */
export interface PaginatedStatutList {
  count?: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results?: Statut[];
}
