/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Rap_app
 * Documentation complète de l'API Rap_App pour l'application mobile et web.
 * OpenAPI spec version: 1.0.0
 */

// ==================== ENUMS ====================

/**
 * Mois concerné (1 = janvier, 12 = décembre)
 * @minimum 0
 * @maximum 32767
 */
export type SuiviJuryMois = typeof SuiviJuryMois[keyof typeof SuiviJuryMois];
// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SuiviJuryMois = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
  NUMBER_6: 6,
  NUMBER_7: 7,
  NUMBER_8: 8,
  NUMBER_9: 9,
  NUMBER_10: 10,
  NUMBER_11: 11,
  NUMBER_12: 12,
} as const;

export type SuiviJuryRequestMois = typeof SuiviJuryRequestMois[keyof typeof SuiviJuryRequestMois];
// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SuiviJuryRequestMois = { ...SuiviJuryMois } as const;

export type PatchedSuiviJuryRequestMois = typeof PatchedSuiviJuryRequestMois[keyof typeof PatchedSuiviJuryRequestMois];
// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchedSuiviJuryRequestMois = { ...SuiviJuryMois } as const;

// ==================== INTERFACES ====================

export interface SuiviJury {
  readonly id?: number;
  /** Centre associé à cet enregistrement */
  readonly centre_id?: number;
  readonly centre_nom?: string;
  /**
   * Année concernée par le suivi (ex: 2024)
   * @minimum 2000
   * @maximum 2147483647
   */
  annee?: number;
  /**
   * Mois concerné (1 = janvier, 12 = décembre)
   * @minimum 0
   * @maximum 32767
   */
  mois?: SuiviJuryMois;
  readonly mois_libelle?: string;
  readonly periode?: string;
  /**
   * Nombre de jurys prévus pour ce mois
   * @minimum 0
   * @maximum 2147483647
   */
  objectif_jury?: number;
  /**
   * Nombre de jurys effectivement réalisés
   * @minimum 0
   * @maximum 2147483647
   */
  jurys_realises?: number;
  readonly pourcentage_atteinte?: number;
  readonly objectif_auto?: number;
  readonly ecart?: number;
  /** Date et heure de création de l'enregistrement */
  readonly created_at?: string;
  /** Date et heure de la dernière modification */
  readonly updated_at?: string;
  /**
   * Utilisateur ayant créé l'enregistrement
   * @nullable
   */
  readonly created_by?: number | null;
  /**
   * Dernier utilisateur ayant modifié l'enregistrement
   * @nullable
   */
  readonly updated_by?: number | null;
  /** Indique si l'objet est actif ou archivé */
  readonly is_active?: boolean;
}

export interface SuiviJuryRequest {
  /**
   * Année concernée par le suivi (ex: 2024)
   * @minimum 2000
   * @maximum 2147483647
   */
  annee?: number;
  /**
   * Mois concerné (1 = janvier, 12 = décembre)
   * @minimum 0
   * @maximum 32767
   */
  mois?: SuiviJuryRequestMois;
  /**
   * Nombre de jurys prévus pour ce mois
   * @minimum 0
   * @maximum 2147483647
   */
  objectif_jury?: number;
  /**
   * Nombre de jurys effectivement réalisés
   * @minimum 0
   * @maximum 2147483647
   */
  jurys_realises?: number;
}

export interface PatchedSuiviJuryRequest {
  /**
   * Année concernée par le suivi (ex: 2024)
   * @minimum 2000
   * @maximum 2147483647
   */
  annee?: number;
  /**
   * Mois concerné (1 = janvier, 12 = décembre)
   * @minimum 0
   * @maximum 32767
   */
  mois?: PatchedSuiviJuryRequestMois;
  /**
   * Nombre de jurys prévus pour ce mois
   * @minimum 0
   * @maximum 2147483647
   */
  objectif_jury?: number;
  /**
   * Nombre de jurys effectivement réalisés
   * @minimum 0
   * @maximum 2147483647
   */
  jurys_realises?: number;
}

export interface PaginatedSuiviJuryList {
  count?: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results?: SuiviJury[];
}

export type SuivisJuryListParams = {
  /** A page number within the paginated result set. */
  page?: number;
  /** Number of results to return per page. */
  page_size?: number;
};
