/**
 * Generated by orval v7.9.0 🍺  
 * Do not edit manually.  
 * Rap_app  
 * Documentation complète de l'API Rap_App pour l'application mobile et web.  
 * OpenAPI spec version: 1.0.0
 */

/* ========================================================
 * 📌 ENUMS CENTRALISÉS : Statuts de VAE
 * ======================================================== */

/**
 * 🧭 Liste des statuts de la VAE (lecture seule)
 */
export const VAE_STATUTS = {
  info: 'info',
  dossier: 'dossier',
  attente_financement: 'attente_financement',
  accompagnement: 'accompagnement',
  jury: 'jury',
  terminee: 'terminee',
  abandonnee: 'abandonnee',
} as const;

/**
 * Statut de la VAE dans les réponses API (lecture seule)
 */
export type VaeStatut = keyof typeof VAE_STATUTS;

/**
 * Statut de la VAE dans les requêtes POST/PUT
 */
export type VAERequestStatut = keyof typeof VAE_STATUTS;

/**
 * Statut de la VAE dans les requêtes PATCH
 */
export type PatchedVAERequestStatut = keyof typeof VAE_STATUTS;

/* ========================================================
 * 📄 INTERFACES VAE
 * ======================================================== */

/**
 * 📄 Serializer principal de la VAE (lecture seule)
 */
export interface Vae {
  readonly id?: number;
  /** Référence unique de la VAE (générée automatiquement si vide) */
  readonly reference?: string;

  /** Centre auquel la VAE est rattachée */
  readonly centre_id?: number;
  readonly centre_nom?: string;

  /** Statut actuel de la VAE */
  statut?: VaeStatut;
  readonly statut_libelle?: string;

  /** Remarques ou informations complémentaires */
  commentaire?: string;

  /** Date de création */
  readonly created_at?: string;

  /** Date de dernière modification */
  readonly updated_at?: string;

  /**
   * Utilisateur ayant créé l'enregistrement
   * @nullable
   */
  readonly created_by?: number | null;

  /**
   * Dernier utilisateur ayant modifié l'enregistrement
   * @nullable
   */
  readonly updated_by?: number | null;

  /** Indique si l'objet est actif ou archivé */
  readonly is_active?: boolean;

  /** Indique si la VAE est en cours */
  readonly is_en_cours?: boolean;

  /** Indique si la VAE est terminée */
  readonly is_terminee?: boolean;

  /** Durée totale en jours */
  readonly duree_jours?: number;

  /** Durée du statut actuel en jours */
  readonly duree_statut_actuel?: number;
}

/**
 * ✍️ Données pour créer ou modifier une VAE
 */
export interface VAERequest {
  /** Statut actuel de la VAE */
  statut?: VAERequestStatut;

  /** Remarques ou informations complémentaires */
  commentaire?: string;
}

/**
 * 🔧 Données partielles pour PATCH VAE
 */
export interface PatchedVAERequest {
  /** Statut actuel de la VAE */
  statut?: PatchedVAERequestStatut;

  /** Remarques ou informations complémentaires */
  commentaire?: string;
}

/* ========================================================
 * 📋 PARAMÈTRES DE LISTE / PAGINATION
 * ======================================================== */

/**
 * 🔍 Paramètres de pagination pour la liste des VAE
 */
export type VaesListParams = {
  /**
   * A page number within the paginated result set.
   */
  page?: number;

  /**
   * Number of results to return per page.
   */
  page_size?: number;
};

/**
 * 📄 Liste paginée des VAE
 */
export interface PaginatedVAEList {
  count?: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results?: Vae[];
}
