/**
 * Generated by orval v7.9.0 🍺  
 * Do not edit manually.  
 * Rap_app  
 * Documentation complète de l'API Rap_App pour l'application mobile et web.  
 * OpenAPI spec version: 1.0.0
 */

/**
 * 🎓 Serializer principal pour les formations.
 * 
 * Sérialise les données complètes d'une formation avec :
 * - Validation métier
 * - Champs relationnels (centre, type_offre, statut)
 * - Données calculées via `to_serializable_dict()`
 */
export interface Formation {
  readonly id?: number;

  /** Nom complet de la formation */
  nom: string;

  /**
   * Date de début
   * @nullable
   */
  start_date?: string | null;

  /**
   * Date de fin
   * @nullable
   */
  end_date?: string | null;

  /**
   * Numéro Kairos
   * @nullable
   */
  num_kairos?: string | null;

  /**
   * Numéro offre
   * @nullable
   */
  num_offre?: string | null;

  /**
   * Numéro produit
   * @nullable
   */
  num_produit?: string | null;

  /** Places prévues CRIF */
  prevus_crif?: number;

  /** Places prévues MP */
  prevus_mp?: number;

  /** Inscrits CRIF */
  inscrits_crif?: number;

  /** Inscrits MP */
  inscrits_mp?: number;

  /**
   * Assistante
   * @nullable
   */
  assistante?: string | null;

  /**
   * Capacité maximale
   * @nullable
   */
  cap?: number | null;

  /** Convocation envoyée */
  convocation_envoie?: boolean;

  /** Entrées en formation */
  entree_formation?: number;

  /** Candidats */
  nombre_candidats?: number;

  /** Entretiens */
  nombre_entretiens?: number;

  /** Événements */
  nombre_evenements?: number;

  /**
   * Dernier commentaire
   * @nullable
   */
  dernier_commentaire?: string | null;

  /** ID du centre associé */
  readonly centre?: number;

  /** ID du type d'offre */
  readonly type_offre?: number;

  /** ID du statut */
  readonly statut?: number;
}

/**
 * 🎓 Données envoyées pour créer ou mettre à jour une formation.
 */
export interface FormationRequest {
  /**
   * Nom complet de la formation
   * @minLength 1
   */
  nom: string;

  /** ID du centre */
  centre_id: number;

  /** ID du type d'offre */
  type_offre_id: number;

  /** ID du statut */
  statut_id: number;

  /**
   * Date de début
   * @nullable
   */
  start_date?: string | null;

  /**
   * Date de fin
   * @nullable
   */
  end_date?: string | null;

  /**
   * Numéro Kairos
   * @nullable
   */
  num_kairos?: string | null;

  /**
   * Numéro offre
   * @nullable
   */
  num_offre?: string | null;

  /**
   * Numéro produit
   * @nullable
   */
  num_produit?: string | null;

  /** Places prévues CRIF */
  prevus_crif?: number;

  /** Places prévues MP */
  prevus_mp?: number;

  /** Inscrits CRIF */
  inscrits_crif?: number;

  /** Inscrits MP */
  inscrits_mp?: number;

  /**
   * Assistante
   * @nullable
   */
  assistante?: string | null;

  /**
   * Capacité maximale
   * @nullable
   */
  cap?: number | null;

  /** Convocation envoyée */
  convocation_envoie?: boolean;

  /** Entrées en formation */
  entree_formation?: number;

  /** Candidats */
  nombre_candidats?: number;

  /** Entretiens */
  nombre_entretiens?: number;

  /** Événements */
  nombre_evenements?: number;

  /**
   * Dernier commentaire
   * @nullable
   */
  dernier_commentaire?: string | null;
}

/**
 * 🔍 Paramètres pour filtrer et paginer la liste des formations.
 */
export type FormationsListParams = {
  /** ID du centre */
  centre?: string;

  /** Date de début minimale (AAAA-MM-JJ) */
  date_debut?: string;

  /** Date de fin maximale (AAAA-MM-JJ) */
  date_fin?: string;

  /** A page number within the paginated result set. */
  page?: number;

  /** Number of results to return per page. */
  page_size?: number;

  /** Filtre les formations avec des places disponibles */
  places_disponibles?: string;

  /** ID du statut */
  statut?: string;

  /** Recherche texte libre (nom, commentaire...) */
  texte?: string;

  /** Champ de tri (ex: -start_date, nom...) */
  tri?: string;

  /** ID du type d'offre */
  type_offre?: string;
};
/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Rap_app
 * Documentation complète de l'API Rap_App pour l'application mobile et web.
 * OpenAPI spec version: 1.0.0
 */

export interface PaginatedFormationList {
  count?: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results?: Formation[];
}
/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Rap_app
 * Documentation complète de l'API Rap_App pour l'application mobile et web.
 * OpenAPI spec version: 1.0.0
 */

/**
 * 🎓 Serializer principal pour les formations.

Sérialise les données complètes d'une formation avec :
- Validation métier
- Champs relationnels (centre, type_offre, statut)
- Données calculées via `to_serializable_dict()`
 */
export interface PatchedFormationRequest {
  /**
   * Nom complet de la formation
   * @minLength 1
   */
  nom?: string;
  /** ID du centre */
  centre_id?: number;
  /** ID du type d'offre */
  type_offre_id?: number;
  /** ID du statut */
  statut_id?: number;
  /**
   * Date de début
   * @nullable
   */
  start_date?: string | null;
  /**
   * Date de fin
   * @nullable
   */
  end_date?: string | null;
  /**
   * Numéro Kairos
   * @nullable
   */
  num_kairos?: string | null;
  /**
   * Numéro offre
   * @nullable
   */
  num_offre?: string | null;
  /**
   * Numéro produit
   * @nullable
   */
  num_produit?: string | null;
  /** Places prévues CRIF */
  prevus_crif?: number;
  /** Places prévues MP */
  prevus_mp?: number;
  /** Inscrits CRIF */
  inscrits_crif?: number;
  /** Inscrits MP */
  inscrits_mp?: number;
  /**
   * Assistante
   * @nullable
   */
  assistante?: string | null;
  /**
   * Capacité maximale
   * @nullable
   */
  cap?: number | null;
  /** Convocation envoyée */
  convocation_envoie?: boolean;
  /** Entrées en formation */
  entree_formation?: number;
  /** Candidats */
  nombre_candidats?: number;
  /** Entretiens */
  nombre_entretiens?: number;
  /** Événements */
  nombre_evenements?: number;
  /**
   * Dernier commentaire
   * @nullable
   */
  dernier_commentaire?: string | null;
}
