/**
 * Generated by orval v7.9.0 🍺  
 * Do not edit manually.  
 * Rap_app  
 * Documentation complète de l'API Rap_App pour l'application mobile et web.  
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer pour l'historique des modifications de prospection.  
 * Fournit les champs formatés et calculés utiles à l'affichage.
 */
export interface HistoriqueProspection {
  readonly id?: number;

  /** ID de la prospection concernée */
  prospection: number;

  /** Date et heure de la modification */
  readonly date_modification?: string;

  /** Ancien statut avant modification */
  ancien_statut: HistoriqueProspectionAncienStatut;
  readonly ancien_statut_display?: string;

  /** Nouveau statut après modification */
  nouveau_statut: HistoriqueProspectionNouveauStatut;
  readonly nouveau_statut_display?: string;

  /** Type de contact (premier_contact / relance) */
  type_contact?: HistoriqueProspectionTypeContact;
  readonly type_contact_display?: string;

  /**
   * Commentaire facultatif
   * @nullable
   */
  commentaire?: string | null;

  /**
   * Résultat de l'action
   * @nullable
   */
  resultat?: string | null;

  /**
   * Date de relance prévue
   * @nullable
   */
  prochain_contact?: string | null;

  /**
   * Moyen de contact utilisé
   * @nullable
   */
  moyen_contact?: HistoriqueProspectionMoyenContact;
  readonly moyen_contact_display?: string;

  readonly jours_avant_relance?: number;
  readonly relance_urgente?: boolean;
  readonly est_recent?: boolean;
  readonly created_by?: string;

  /**
   * Renvoie un objet avec le nom du statut + icône + couleur CSS
   */
  readonly statut_avec_icone?: HistoriqueProspectionStatutAvecIcone;
}

/**
 * Ancien statut avant modification
 */
export type HistoriqueProspectionAncienStatut = typeof HistoriqueProspectionAncienStatut[keyof typeof HistoriqueProspectionAncienStatut];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HistoriqueProspectionAncienStatut = {
  a_faire: 'a_faire',
  en_cours: 'en_cours',
  a_relancer: 'a_relancer',
  acceptee: 'acceptee',
  refusee: 'refusee',
  annulee: 'annulee',
  non_renseigne: 'non_renseigne',
} as const;

/**
 * Nouveau statut après modification
 */
export type HistoriqueProspectionNouveauStatut = typeof HistoriqueProspectionNouveauStatut[keyof typeof HistoriqueProspectionNouveauStatut];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HistoriqueProspectionNouveauStatut = {
  a_faire: 'a_faire',
  en_cours: 'en_cours',
  a_relancer: 'a_relancer',
  acceptee: 'acceptee',
  refusee: 'refusee',
  annulee: 'annulee',
  non_renseigne: 'non_renseigne',
} as const;

/**
 * Moyen de contact utilisé
 * @nullable
 */
export type HistoriqueProspectionMoyenContact =
  | typeof HistoriqueProspectionMoyenContact[keyof typeof HistoriqueProspectionMoyenContact]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HistoriqueProspectionMoyenContact = {
  email: 'email',
  telephone: 'telephone',
  visite: 'visite',
  reseaux: 'reseaux',
  '': '',
} as const;

/**
 * Type de contact (premier_contact / relance)
 */
export type HistoriqueProspectionTypeContact = typeof HistoriqueProspectionTypeContact[keyof typeof HistoriqueProspectionTypeContact];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HistoriqueProspectionTypeContact = {
  premier_contact: 'premier_contact',
  relance: 'relance',
} as const;

/**
 * Renvoie un objet avec le nom du statut + icône + couleur CSS
 */
export type HistoriqueProspectionStatutAvecIcone = { [key: string]: unknown };

/**
 * Valeurs possibles pour le champ `nouveau_statut` dans la liste filtrée
 */
export type HistoriquesProspectionListNouveauStatut =
  typeof HistoriquesProspectionListNouveauStatut[keyof typeof HistoriquesProspectionListNouveauStatut];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HistoriquesProspectionListNouveauStatut = {
  a_faire: 'a_faire',
  a_relancer: 'a_relancer',
  acceptee: 'acceptee',
  annulee: 'annulee',
  en_cours: 'en_cours',
  non_renseigne: 'non_renseigne',
  refusee: 'refusee',
} as const;

/**
 * Valeurs possibles pour le champ `type_contact` dans la liste filtrée
 */
export type HistoriquesProspectionListTypeContact =
  typeof HistoriquesProspectionListTypeContact[keyof typeof HistoriquesProspectionListTypeContact];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HistoriquesProspectionListTypeContact = {
  premier_contact: 'premier_contact',
  relance: 'relance',
} as const;

/**
 * 🔍 Paramètres de filtre pour la liste des historiques de prospection
 */
export type HistoriquesProspectionListParams = {
  /**
   * Statut après la modification
   */
  nouveau_statut?: HistoriquesProspectionListNouveauStatut;

  /**
   * Which field to use when ordering the results.
   */
  ordering?: string;

  /**
   * A page number within the paginated result set.
   */
  page?: number;

  /**
   * Number of results to return per page.
   */
  page_size?: number;

  /** ID de la prospection liée */
  prospection?: number;

  /**
   * A search term.
   */
  search?: string;

  /**
   * Type de contact utilisé
   */
  type_contact?: HistoriquesProspectionListTypeContact;
};
/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Rap_app
 * Documentation complète de l'API Rap_App pour l'application mobile et web.
 * OpenAPI spec version: 1.0.0
 */

export interface PaginatedHistoriqueProspectionList {
  count?: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results?: HistoriqueProspection[];
}
