/**
 * Generated by orval v7.9.0 🍺  
 * Do not edit manually.  
 * Rap_app  
 * Documentation complète de l'API Rap_App pour l'application mobile et web.  
 * OpenAPI spec version: 1.0.0
 */

/**
 * 📝 Serializer en lecture seule pour les logs utilisateur.
 *
 * Fournit une vue enrichie des logs, incluant des champs calculés pour :
 * - le modèle concerné (`get_model`)
 * - l'utilisateur ayant réalisé l'action (`get_user`)
 * - la date de l'action formatée (`get_date`)
 */
export interface LogUtilisateur {
  readonly id?: number;

  /** Type d'action réalisée (création, modification, suppression). */
  readonly action?: string;

  /** Nom du modèle concerné par l'action. */
  readonly model?: string;

  /** Identifiant de l'objet modifié. */
  readonly object_id?: number;

  /** Détails de l'action enregistrée. */
  readonly details?: string;

  /** Nom de l'utilisateur ayant effectué l'action. */
  readonly user?: string;

  /** Date et heure de l'action (format : AAAA-MM-JJ HH:MM). */
  readonly date?: string;
}

/**
 * 🔍 Paramètres de filtre et pagination pour la liste des logs utilisateur.
 */
export type LogsListParams = {
  /** Champ de tri (ex: date, -action, etc.) */
  ordering?: string;

  /** Page courante */
  page?: number;

  /** Nombre de résultats par page */
  page_size?: number;

  /** Recherche texte libre (filtre) */
  search?: string;
};
/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Rap_app
 * Documentation complète de l'API Rap_App pour l'application mobile et web.
 * OpenAPI spec version: 1.0.0
 */


export interface PaginatedLogUtilisateurList {
  count?: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results?: LogUtilisateur[];
}
