/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Rap_app
 * Documentation complète de l'API Rap_App pour l'application mobile et web.
 * OpenAPI spec version: 1.0.0
 */

export type TestTokenRetrieve200 = {
  success?: boolean;
  message?: string;
  user_id?: number;
  username?: string;
  email?: string;
  role?: string;
  is_staff?: boolean;
  is_superuser?: boolean;
};
