/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Rap_app
 * Documentation complète de l'API Rap_App pour l'application mobile et web.
 * OpenAPI spec version: 1.0.0
 */

/**
 * =============================
 * Enum unique des noms internes du type d'offre (choix prédéfinis)
 * =============================
 */
export const TypeOffreNomObj = {
  crif: 'crif',
  alternance: 'alternance',
  poec: 'poec',
  poei: 'poei',
  tosa: 'tosa',
  autre: 'autre',
  non_defini: 'non_defini',
} as const;

/**
 * Type TypeOffreNom : union des valeurs de l'enum TypeOffreNom
 */
export type TypeOffreNom = typeof TypeOffreNomObj[keyof typeof TypeOffreNomObj];

/**
 * =============================
 * Types et Interfaces principales
 * =============================
 */

/**
 * 🎯 Représentation complète du modèle TypeOffre.
 *
 * Expose les champs utiles pour l’interface frontend, avec validation métier,
 * couleurs personnalisables, et types prédéfinis ou personnalisés.
 */
export interface TypeOffre {
  readonly id?: number;
  /** Nom interne du type d'offre (choix prédéfinis). */
  nom?: TypeOffreNom;
  readonly nom_display?: string;
  /**
   * Texte personnalisé pour les types d'offre marqués comme 'autre'.
   * @maxLength 255
   */
  autre?: string;
  /**
   * Couleur affichée pour ce type (code hexadécimal, ex: #FF5733).
   * @maxLength 7
   * @nullable
   */
  couleur?: string | null;
  readonly badge_html?: string;
  /** True si le champ 'autre' est renseigné. */
  readonly is_personnalise?: boolean;
  readonly formations_count?: number;
  /** Date et heure de création de l'enregistrement */
  readonly created_at?: string;
  /** Date et heure de la dernière modification */
  readonly updated_at?: string;
  /**
   * Utilisateur ayant créé l'enregistrement
   * @nullable
   */
  readonly created_by?: number | null;
  /**
   * Dernier utilisateur ayant modifié l'enregistrement
   * @nullable
   */
  readonly updated_by?: number | null;
  /** Indique si l'objet est actif ou archivé */
  readonly is_active?: boolean;
}

/**
 * 🎯 Représentation des données nécessaires pour créer ou mettre à jour un TypeOffre (request).
 */
export interface TypeOffreRequest {
  /** Nom interne du type d'offre (choix prédéfinis). */
  nom?: TypeOffreNom;
  /**
   * Texte personnalisé pour les types d'offre marqués comme 'autre'.
   * @maxLength 255
   */
  autre?: string;
  /**
   * Couleur affichée pour ce type (code hexadécimal, ex: #FF5733).
   * @maxLength 7
   * @nullable
   */
  couleur?: string | null;
}

/**
 * 🎯 Représentation partielle pour PATCH (mise à jour partielle) du TypeOffre.
 */
export interface PatchedTypeOffreRequest {
  /** Nom interne du type d'offre (choix prédéfinis). */
  nom?: TypeOffreNom;
  /**
   * Texte personnalisé pour les types d'offre marqués comme 'autre'.
   * @maxLength 255
   */
  autre?: string;
  /**
   * Couleur affichée pour ce type (code hexadécimal, ex: #FF5733).
   * @maxLength 7
   * @nullable
   */
  couleur?: string | null;
}

/**
 * =============================
 * Types d'API / Pagination / Params
 * =============================
 */

/**
 * Paramètres de requête pour la liste paginée des TypeOffre.
 */
export type TypeoffresListParams = {
  /**
   * Champ utilisé pour ordonner les résultats (ex: 'nom', '-created_at').
   */
  ordering?: string;
  /**
   * Numéro de page dans la pagination.
   */
  page?: number;
  /**
   * Nombre de résultats par page.
   */
  page_size?: number;
  /**
   * Terme de recherche pour filtrer les résultats.
   */
  search?: string;
};

/**
 * Résultat paginé pour la liste de TypeOffre.
 */
export interface PaginatedTypeOffreList {
  count?: number;
  /** @nullable URL vers la page suivante, null si dernière page */
  next?: string | null;
  /** @nullable URL vers la page précédente, null si première page */
  previous?: string | null;
  results?: TypeOffre[];
}
